test-functiondeclaration:
	babel ./examples/sample-functiondeclaration.js --plugins ../babel-jsdoced.js

test-functionexpression:
	babel ./examples/sample-functionexpression.js --plugins ../babel-jsdoced.js
